"""create_users_table_safely

Revision ID: c99e184c174e
Revises: 
Create Date: 2026-07-25 19:06:37.393534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c99e184c174e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    op.drop_table('chat_history: id, user_id, title, folder, messages')
    op.drop_table('notices')
    op.drop_table('syllabus')
    op.drop_table('chat_sessions')
    op.drop_table('documents')
    op.drop_table('ai_training_logs')
    op.drop_table('debate_history')
    op.drop_table('smart_routines')
    op.drop_table('subscriptions')
    op.drop_table('support_tickets')
    op.drop_table('api_keys')
    op.drop_table('study_sessions')
    op.drop_table('agent_memory')
    op.drop_table('security_logs')
    op.drop_table('manual_payments')
    op.drop_table('audit_logs')
    op.drop_table('profiles')
    op.drop_table('usage_tracking')
    op.drop_table('study_plans')
    op.drop_table('user_profiles')
    op.drop_table('academic_analytics')
    op.drop_table('student_results')
    op.drop_table('billing_ledger')
    op.drop_table('study_analytics')
    op.drop_table('knowledge_base_logs')
    op.drop_table('transactions')
    op.drop_index(op.f('gstu_documents_embedding_idx'), table_name='gstu_documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('gstu_documents')
    op.drop_table('user_roles')
    op.drop_table('faculty_sensitive_data')
    op.drop_table('ai_feedback: id, user_id, chat_id, rating (like/dislike), feedb')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Student'::text"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('users_student_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(op.f('users_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'department')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_id_fkey'), 'users', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_student_id_key'), 'users', ['student_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Student'::text"))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'email')
    op.create_table('ai_feedback: id, user_id, chat_id, rating (like/dislike), feedb',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_feedback: id, user_id, chat_id, rating (like/dislike), _pkey'))
    )
    op.create_table('faculty_sensitive_data',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('confidential_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('faculty_sensitive_data_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('faculty_sensitive_data_pkey'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'user'::text"), autoincrement=False, nullable=False),
    sa.Column('granted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("role = ANY (ARRAY['admin'::text, 'moderator'::text, 'user'::text])", name=op.f('user_roles_role_check')),
    sa.ForeignKeyConstraint(['granted_by'], ['auth.users.id'], name=op.f('user_roles_granted_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('user_roles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role', name=op.f('user_roles_pkey'))
    )
    op.create_table('gstu_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gstu_documents_pkey'))
    )
    op.create_index(op.f('gstu_documents_embedding_idx'), 'gstu_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('gateway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("gateway = ANY (ARRAY['bkash'::text, 'sslcommerz'::text, 'stripe'::text])", name=op.f('transactions_gateway_check')),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'cancelled'::text])", name=op.f('transactions_status_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('transactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_table('knowledge_base_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('course_tag', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'embedded'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_base_logs_pkey'))
    )
    op.create_table('study_analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('topic_dissected', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comprehension_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.CheckConstraint('comprehension_score >= 1 AND comprehension_score <= 10', name=op.f('study_analytics_comprehension_score_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('study_analytics_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('study_analytics_pkey'))
    )
    op.create_table('billing_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('invoice_reference', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_gateway', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('transaction_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bank_trx_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("transaction_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])", name=op.f('billing_ledger_transaction_status_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('billing_ledger_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('billing_ledger_pkey')),
    sa.UniqueConstraint('bank_trx_id', name=op.f('billing_ledger_bank_trx_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('invoice_reference', name=op.f('billing_ledger_invoice_reference_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('student_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cgpa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('student_results_pkey')),
    sa.UniqueConstraint('student_id', name=op.f('student_results_student_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('academic_analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('course_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quiz_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productivity_boost_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('academic_analytics_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('academic_analytics_pkey'))
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('department', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('subscription_tier', sa.TEXT(), server_default=sa.text("'free'::text"), autoincrement=False, nullable=True),
    sa.Column('pro_expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reward_credits', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referral_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referred_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referral_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('current_semester', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_cgpa', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('academic_weaknesses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('total_study_hours', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('core_interest', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('career_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_onboarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'Student'::text"), autoincrement=False, nullable=True),
    sa.Column('total_xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('current_streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('rank_title', sa.TEXT(), server_default=sa.text("'Freshman Analyst'::text"), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roll_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('user_profiles_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey')),
    sa.UniqueConstraint('referral_code', name=op.f('user_profiles_referral_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_profiles_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('study_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_plan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Active'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('study_plans_pkey'))
    )
    op.create_table('usage_tracking',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('daily_requests', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tokens_input', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tokens_output', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('abuse_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('blocked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_reset', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('usage_tracking_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('usage_tracking_pkey'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('profiles_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['auth.users.id'], name=op.f('audit_logs_actor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('manual_payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trx_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), server_default=sa.text('500'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('manual_payments_pkey'))
    )
    op.create_table('security_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('malicious_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('security_logs_pkey'))
    )
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('target_agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('visibility_scope', sa.TEXT(), server_default=sa.text("'private'::text"), autoincrement=False, nullable=True),
    sa.Column('encrypted_payload', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("visibility_scope = ANY (ARRAY['private'::text, 'shared'::text, 'consent_based'::text])", name=op.f('agent_memory_visibility_scope_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('agent_memory_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_memory_pkey'))
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hours', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('mood', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('study_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('study_sessions_pkey'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('key_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['auth.users.id'], name=op.f('api_keys_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey')),
    sa.UniqueConstraint('key_hash', name=op.f('api_keys_key_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticket_status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.TEXT(), server_default=sa.text("'Unknown'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('support_tickets_pkey'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), server_default=sa.text("'free'::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('gateway_customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("plan = ANY (ARRAY['free'::text, 'premium'::text, 'enterprise'::text])", name=op.f('subscriptions_plan_check')),
    sa.CheckConstraint("status = ANY (ARRAY['active'::text, 'past_due'::text, 'canceled'::text])", name=op.f('subscriptions_status_check')),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('subscriptions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_table('smart_routines',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('routine_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('smart_routines_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('smart_routines_pkey'))
    )
    op.create_table('debate_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('argument', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('debate_history_pkey'))
    )
    op.create_table('ai_training_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('user_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('topic_tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('ai_training_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_training_logs_pkey'))
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.TEXT(), server_default=sa.text("'private'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint("visibility = ANY (ARRAY['private'::text, 'public'::text, 'department_only'::text])", name=op.f('documents_visibility_check')),
    sa.ForeignKeyConstraint(['owner_id'], ['auth.users.id'], name=op.f('documents_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agent_type', sa.TEXT(), server_default=sa.text("'gstu_ir'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('chat_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_sessions_pkey'))
    )
    op.create_table('syllabus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semester', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('course_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('room', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('syllabus_pkey'))
    )
    op.create_table('notices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'published'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notices_pkey'))
    )
    op.create_table('chat_history: id, user_id, title, folder, messages',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history: id, user_id, title, folder, messages_pkey'))
    )
    op.create_table('chat_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message_role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('is_summarized', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("message_role = ANY (ARRAY['user'::text, 'ai'::text, 'system'::text])", name=op.f('chat_history_message_role_check')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('chat_history_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    # ### end Alembic commands ###
